name: contact_bloc
description: Contact - Bloc.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  mocktail: ^1.0.3
  test: ^1.25.5

dependency_overrides:
  test_api: ^0.7.1
  meta: ^1.14.0

flutter:
  uses-material-design: true
